#test1_change
---
# this file assumes Automation Hub is the default source
collections:

- name: community.libvirt
  version: 1.0.0
  source: https://galaxy.ansible.com

- name: community.vmware
  version: 1.0.0
  source: https://galaxy.ansible.com

- name: community.general

- name: ansible.windows
  version: 1.10.0
  source: https://galaxy.ansible.com
  
- name: community.windows
  version: 1.3.0
  source: https://galaxy.ansible.com

- name: chocolatey.chocolatey
  version: 1.2.0
  source: https://galaxy.ansible.com