---
- hosts: local_inventory
  become_user: yes
  gather_facts: no
  vars:
    ansible_win_user: "{{ win_username }}"
    ansible_win_password: "{{ win_password }}"
  tasks:
    - name: Create in memory inventory with created VM
      add_host:
        name: "{{ windows_hostname }}"
        groups: windows_server
        ansible_user: '{{ ansible_win_user }}'
        ansible_pass: '{{ ansible_win_password }}'
        ansible_hostname: "{{ windows_hostname }}"
        ansible_port: 5985
        ansible_connection: winrm
        ansible_winrm_transport: 'ntlm'
        ansible_winrm_server_cert_validation: ignore
      no_log: true

- hosts: windows_server
  gather_facts: no
  tasks:
    - name: Ping the Machine
      win_ping: 

    - name: Include role to install windows service
      include_role:
         name: install_choco_windows
