---
- hosts: local_inventory
  gather_facts: false
  tasks:
    - name: Include role to create Windows VM
      include_role:
        name: create_win_vm
    - name: Set Fact for workflow template
      set_fact:
          windows_ip_address: "{{ windows_vm_ip }}"
          windows_hostname: "{{ vm_name }}.iisl.lab"

    - name: Creating a new file to save the ip address and hostname of the machine
      template:
        src: "/root/Ansible-Core/vm_host_detail.j2"
        dest: "/root/Ansible-Core/vm_host_detail.yml"
      delegate_to: localhost

- hosts: dns_servers
  gather_facts: no
  tasks:
    - name: Include var file
      include_vars:
        file: '/root/Ansible-Core/vm_host_detail.yml'

    - name: debug variables from previous play
      debug:
        msg: "{{ windows_hostname }}"
        
    - name: debug variables from previous play
      debug:
        msg: "{{ windows_ip_address }}"

    - name: Configure the DNS server
      include_role:
        name: configure_dns_server

- hosts: local_inventory
  gather_facts: no
  tasks:
    - name: Include var file
      include_vars:
        file: '/root/Ansible-Core/vm_host_detail.yml'

    - name: Create in memory inventory with created VM
      add_host:
        name: "{{ windows_hostname }}"
        ansible_host: "{{ windows_ip_address }}"
        groups: windows_server
        ansible_user: '{{ ansible_win_user }}'
        ansible_pass: '{{ ansible_win_password }}'
        ansible_port: 5985
        ansible_connection: winrm
        ansible_winrm_transport: 'ntlm'
        ansible_winrm_server_cert_validation: ignore
      no_log: true

- hosts: windows_server
  gather_facts: no
  tasks:
    - name: Ping the Machine
      win_ping: 
    
    - name: Install Windows Services and provision a Web Server
      include_role:
        name: install_windows_service

    - name: Install Choco Pacakges
      include_role:
        name: install_choco_windows