---
- hosts: all
  tasks:
   - name: Include task to provision windows machine
     include_tasks: create_windows_vm.yml

   - name: Include task to configure DNS server
     include_tasks: configure_dns_server.yml

