---
# tasks file for cerate_AD_user
- name: "Create a user"
  community.windows.win_domain_user:
    firstname: "{{ ad_firstname }}"
    surname: "{{ ad_lastname }}"
    name: "{{ ad_firstname }}"
    password: "{{ ad_password }}"
    groups: Administrators
    state: present

