---
# tasks file for create_windows_vm
- name: Select Windows 2016 template
  set_fact:
    windows_template: "windows2016_template"
  when: vm_template == "Windows_2016"

- name: Select Windows 2019 template
  set_fact:
    windows_template: "windows2019_template"
  when: vm_template == "Windows_2019"

- name: Provision Windows machine
  vmware_guest:
    folder: "RHEL-Automation"
    template: "{{ windows_template }}"
    validate_certs: no
    name: "{{ vm_name }}"
    state: poweredon
    cluster: "RHEL-Automation"
    datastore: "Demo-Datastore01"
    datacenter: "Plainview"
    hardware:
      memory_mb: 4096
      num_cpus: 2
    networks:
      - name: "RHEL-Automation - vLAN 102"
        type: dhcp
        domain: "{{ vm_name }}.iisl.lab"
        dns_servers:
          - 192.168.2.201
    customization:
      hostname: '{{ vm_name }}.iisl.lab'
      dns_servers:
        - 192.168.2.201
      autologon: yes
      dns_suffix:
        - "crucible.iisl.lab"
        - "iisl.lab"
      domain: 'iisl.lab'
      state: started
      runonce:
        - powershell.exe -ExecutionPolicy Unrestricted -File C:\Windows\Temp\ConfigureRemotingForAnsible.ps1 -ForceNewSSLCert -EnableCredSSP
    wait_for_ip_address: yes
    wait_for_customization: yes
  delegate_to: localhost
  register: windows_vm

- name: Gather vmware host facts
  community.vmware.vmware_host_facts:
    hostname: cmrv-vc01.crucible.iisl.com
    username: bmuggalla@CRUCIBLE.iisl.com
    password: Temp!234
    esxi_hostname: '{{ vm_name }}.iisl.lab'
  register: host_facts
  delegate_to: localhost

- debug:
    msg: "{{ host_facts }}"
#- name: Run powershell command to pertain windows VM IP address
#  win_shell: |
#    Get-NetIPAddress
#  delegate_to: wintest.iisl.lab
#  register: vm_info

#- name: Run powershell command to pertain windows VM IP address
#  ansible.windows.win_shell: ipconfig
#  args:
#    executable: cmd
#  delegate_to: "{{ vm_name }}.iisl.lab"
#  register: vm_info

- debug:
    msg: "{{ vm_info }}"

#- name: Check the VMware tools status until it started
#  vmware_guest_info:
#    hostname: ansible_windows_bhanu
#    username: bmuggalla@CRUCIBLE.iisl.com
#    password: Temp!234
#    datacenter: "Plainview"
#  register: info
#  retries: 60
#  delay: 5
#  until: info.instance.guest_tools_status == "guestToolsRunning"

#- name: Run commands on guest OS to pertain IP address
#  vmware_vm_shell:
#    vm_id: ansible_windows_bhanu
#    vm_username: bmuggalla@CRUCIBLE.iisl.com
#    vm_password: Temp!234
#    vm_shell: ipconfig
#  register: shell_output
#
#- debug:
#    msg: "{{ shell_output }}"

- name: debug ip address of vm created
  set_fact:
    windows_vm_ip: "{{ windows_vm.instance.hw_eth0.ipaddresses[0] }}"  #hel_vm.instance.ipv4

- name: Displaying success message
  debug:
    msg: "The VM Has been provisioned successfully"

- name: Set stats for workflow template
  set_stats:
    data:
      windows_ip_address: "{{ windows_vm_ip }}"
      windows_hostname: "{{ vm_name }}.iisl.lab"
